# Generated by Django 3.2.5 on 2021-09-06 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
            ],
            options={
                'verbose_name': 'MA',
                'verbose_name_plural': 'MAs',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dso_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'DSO',
                'verbose_name_plural': 'DSOs',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('wallet_no', models.CharField(max_length=20, verbose_name='Wallet No.')),
                ('shop_name', models.CharField(max_length=200, verbose_name='Shop Name')),
                ('shop_address', models.TextField(blank=True, verbose_name='Shop Address')),
                ('qr_string', models.CharField(blank=True, max_length=200, verbose_name='QR String')),
                ('agent_type', models.CharField(choices=[('agent', 'Agent'), ('bkash_care_agent', 'bKash Care Agent'), ('dao', 'DAO')], default='agent', max_length=50, verbose_name='Agent Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=50, verbose_name='Status')),
                ('reg_capability', models.CharField(choices=[('no_reg', 'No Registration Capability'), ('digital', 'Digital'), ('digital_ussd', 'Digital + USSD')], default='no_reg', max_length=50, verbose_name='Registration Capability')),
                ('geo_code', models.CharField(blank=True, max_length=50, verbose_name='GEO Code')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.area', verbose_name='Area')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.distributor', verbose_name='Distributor')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.district', verbose_name='District')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.division', verbose_name='Division')),
                ('dso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.dso', verbose_name='DSO')),
                ('ma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.ma', verbose_name='MA')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.region', verbose_name='Region')),
                ('union', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.union', verbose_name='Union/Paurashava')),
                ('upazila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.upazila', verbose_name='Thana/Upazila')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
