# Generated by Django 3.2.5 on 2021-09-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='mobile',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='ma',
            name='mobile',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mobile'),
        ),
    ]
