# Generated by Django 3.2.5 on 2021-09-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20210912_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=100, verbose_name='Device ID')),
                ('dso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.dso', verbose_name='DSO')),
            ],
            options={
                'verbose_name': 'Device ID',
                'verbose_name_plural': 'Device IDs',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
