# Generated by Django 3.2.5 on 2021-09-06 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('agent_absent', 'Agent Absent'), ('shop_closed', 'Shop Closed'), ('shop_relocated', 'Shop Relocated')], max_length=50, verbose_name='Status')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent', verbose_name='Agent')),
                ('dso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.dso', verbose_name='DSO')),
            ],
            options={
                'verbose_name': 'Visit History',
                'verbose_name_plural': 'Visit Histories',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Amount')),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=50, verbose_name='Type')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.visithistory', verbose_name='Visit')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
