# Generated by Django 3.2.5 on 2021-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('collected', 'Collected'), ('distributed', 'Distributed')], max_length=50, verbose_name='Type'),
        ),
    ]
